server {
    listen 80;
    server_name 72.167.49.115;

    location / {
        include proxy_params;
        proxy_pass http://unix:/srv/ZillowGHLIntegration/zillow-ghl.sock;
    }

    location /static {
        alias /srv/ZillowGHLIntegration/static;
    }
}
