server {
    listen 80;
    server_name 72.167.49.115;

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/html/zillow-ghl.sock;
    }

    location /static {
        alias /var/www/html/static;
    }
}
